import { Product } from './Product';

export const PRODUCTS: Product[] = [
  { id: 1,
    name: 'Item 1',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 600,
    discount: 20,
    quantity: 20
  },
  { id: 2,
    name: 'Item 2',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 340,
    discount: 23,
    quantity: 20
  },
  { id: 3,
    name: 'Item 3',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 170,
    discount: 20,
    quantity: 20
  },
  { id: 4,
    name: 'Item 4',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 300,
    discount: 16,
    quantity: 20
  },
  { id: 5,
    name: 'Item 5',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 130,
    discount: 14,
    quantity: 20
  },
  { id: 6,
    name: 'Item 6',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 900,
    discount: 12,
    quantity: 20
  },
  { id: 7,
    name: 'Item 7',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 800,
    discount: 19,
    quantity: 20
  },
  { id: 8,
    name: 'Item 8',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 210,
    discount: 11,
    quantity: 20
  },
  { id: 9,
    name: 'Item 9',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 300,
    discount: 8,
    quantity: 20
  },
  { id: 10,
    name: 'Item 10',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 510,
    discount: 40,
    quantity: 20
  },
  { id: 11,
    name: 'Item 11',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 950,
    discount: 17,
    quantity: 20
  },
  { id: 12,
    name: 'Item 12',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 750,
    discount: 12,
    quantity: 20
  },
  { id: 13,
    name: 'Item 13',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 320,
    discount: 30,
    quantity: 20
  },
  { id: 14,
    name: 'Item 14',
    description: '',
    image: 'assets/image/laptop.jpg',
    price: 900,
    quantity: 20
  }
]
